---
- name: Get stat of Kap
  ansible.builtin.stat:
    path: /Applications/Kap.app
  register: kap_app

- name: Skip Install
  ansible.builtin.debug:
    msg: "Kap has already been installed"
  when: kap_app.stat.islnk is defined

- name:
  community.general.homebrew_cask:
    name:
      - kap
    state: latest
    greedy: yes
    accept_external_apps: yes
  when: kap_app.stat.islnk is not defined
