---
- name: Get stat of alfred
  ansible.builtin.stat:
    path: /Applications/Alfred 4.app
  register: alfred_app

- name: Skip Install
  ansible.builtin.debug:
    msg: "Alfred has already been installed"
  when: alfred_app.stat.islnk is defined

- name: Install
  community.general.homebrew_cask:
    name:
      - alfred
    state: latest
    greedy: yes
    accept_external_apps: yes
  when: alfred_app.stat.islnk is not defined
