source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/vim-plug/init.vim
source $HOME/.config/nvim/keys/mappings.vim
source $HOME/.config/nvim/general/colorscheme.vim
source $HOME/.config/nvim/plug-config/better-whitespace.vim
source $HOME/.config/nvim/plug-config/dashboard.vim
source $HOME/.config/nvim/plug-config/dirvish.vim
source $HOME/.config/nvim/plug-config/eunech.vim
source $HOME/.config/nvim/plug-config/lightline.vim
source $HOME/.config/nvim/plug-config/lsp.vim
source $HOME/.config/nvim/plug-config/lsp-saga.vim
source $HOME/.config/nvim/plug-config/nvim-autopairs.vim
source $HOME/.config/nvim/plug-config/nvim-compe.vim
source $HOME/.config/nvim/plug-config/telescope.vim
source $HOME/.config/nvim/plug-config/treesitter.vim
