---
- name:
  community.general.homebrew_cask:
    name:
      - kitty
    state: latest

- name: Config folder
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/kitty"
    state: directory

- name: Configuration
  ansible.builtin.copy:
    src: "kitty.conf"
    dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf"

- name: Create symlink to kitty.conf
  ansible.builtin.file:
    src: "kitty.conf"
    dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf"
    state: link

- name: Themes
  ansible.builtin.copy:
    src: "current-theme.conf"
    dest: "{{ ansible_user_dir }}/.config/kitty/current-theme.conf"

- name: Create symlink to kitty.conf
  ansible.builtin.file:
    src: "current-theme.conf"
    dest: "{{ ansible_user_dir }}/.config/kitty/current-theme.conf"
    state: link
