---
- name: Get stats of the kitty directory
  ansible.builtin.stat:
    path:  "{{ ansible_user_dir }}/.config/kitty"
  register: kitty_sym

- name: Print a debug message
  ansible.builtin.debug:
    msg: "Kitty directory exists and is a symlink"
  when: kitty_sym.stat.islnk is defined and kitty_sym.stat.islnk

- name: Create symlink to kitty directory
  ansible.builtin.file:
    src: "{{ ansible_user_dir}}/dotfiles/roles/kitty/files"
    dest: "{{ ansible_user_dir }}/.config/kitty"
    state: link
    force: true
  when: kitty_sym.stat.islnk is not defined
