---
- name: Existing Install
  stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: install

- name: Clone oh-my-zsh
  ansible.builtin.git:
    clone: yes
    depth: 1
    repo: https://github.com/ohmyzsh/ohmyzsh
    dest: "{{ ansible_user_dir }}/.oh-my-zsh"
    single_branch: yes
    update: yes
  when: not install.stat.exists

- name: Get stats of the .zshrc file
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.zshrc"
  register: zshrc_sym

- name: Get stats of the zshrc function file
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh/custom/function.zsh"
  register: function_sym

- name: Print a debug message
  ansible.builtin.debug:
    msg: ".zshrc path exists and is a symlink"
  when: zshrc_sym.stat.islnk is defined and zshrc_sym.stat.islnk

- name: Print a debug message
  ansible.builtin.debug:
    msg: "function.zsh path exists and is a symlink"
  when: function_sym.stat.islnk is defined and function_sym.stat.islnk

- name: Create symlink to .zshrc
  ansible.builtin.file:
    src: "{{ ansible_user_dir}}/dotfiles/roles/oh-my-zsh/files/.zshrc"
    path: "{{ ansible_user_dir }}/.zshrc"
    state: link
    force: true
  when: zshrc_sym.stat.islnk is not defined

- name: Create symlink to .zshrc functions
  ansible.builtin.file:
    src: "{{ ansible_user_dir}}/dotfiles/roles/oh-my-zsh/files/function.zsh"
    path: "{{ ansible_user_dir }}/.oh-my-zsh/custom/function.zsh"
    state: link
    force: true
  when: function_sym.stat.islnk is not defined

- name: Clone fast-syntax-highlighting
  ansible.builtin.git:
    clone: yes
    depth: 1
    repo: https://github.com/z-shell/F-Sy-H.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/F-Sy-H"
    single_branch: yes
    update: yes

- name: Clone zsh-autosuggestions
  ansible.builtin.git:
    clone: yes
    depth: 1
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    single_branch: yes
    update: yes

- name: Clone zsh-completions
  ansible.builtin.git:
    clone: yes
    depth: 1
    repo: https://github.com/zsh-users/zsh-completions
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-completions"
    single_branch: yes
    update: yes

- name: Clone zsh-z
  ansible.builtin.git:
    clone: yes
    depth: 1
    repo: https://github.com/agkozak/zsh-z
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-z"
    single_branch: yes
    update: yes

- name: Clone spaceship-prompt
  ansible.builtin.git:
    clone: yes
    depth: 1
    repo: https://github.com/spaceship-prompt/spaceship-prompt
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/spaceship-prompt"
    single_branch: yes
    update: yes

- name: Get stats of the spaceship.zsh-theme file
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
  register: prompt_sym

- name: Print a debug message
  ansible.builtin.debug:
    msg: "spaceship.zsh-theme path exists and is a symlink"
  when: prompt_sym.stat.islnk is defined and prompt_sym.stat.islnk

- name: Create symlink spaceship.zsh-theme
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
    path: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
    state: link
    force: true
  when: prompt_sym.stat.islnk is not defined
