---
- name: Copy .gitconfig
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.gitconfig"
    src: ".gitconfig"

- name: Create symlink to .gitconfig
  ansible.builtin.file:
    src: "{{ ansible_user_dir}}/dotfiles/roles/git/files/.gitconfig"
    path: "{{ ansible_user_dir }}/.gitconfig"
    state: link
    force: true

- name: Copy .gitignore_global
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.gitignore_global"
    src: ".gitignore_global"

- name: Create symlink to .gitignore_global
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.gitignore_global"
    src: "{{ ansible_user_dir}}/dotfiles/roles/git/files/.gitignore_global"
    state: link
    force: true

- name: Set user name and password
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/.gitconfig.local"
    src: "gitconfig.local.j2"
