---
- name: Get stats of the .tmux.conf file
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.tmux.conf"
  register: tmux_sym

- name: Print a debug message
  ansible.builtin.debug:
    msg: ".tmux.conf path exists and is a symlink"
  when: tmux_sym.stat.islnk is defined and tmux_sym.stat.islnk

- name: Link .tmux.conf
  ansible.builtin.file:
    src: "{{ ansible_user_dir}}/dotfiles/roles/tmux/files/.tmux.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    state: link
  when: tmux_sym.stat.islnk is not defined
