---
- name: Get stats of the starship file
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.config/starship.toml"
  register: starship_sym

- name: Print a debug message
  ansible.builtin.debug:
    msg: "starship.toml already exists and is a symlink"
  when: starship_sym.stat.islnk is defined and starship_sym.stat.islnk

- name: Create symlink to starship.toml file
  ansible.builtin.file:
    src: "{{ ansible_user_dir}}/dotfiles/roles/starship/files/starship.toml"
    dest: "{{ ansible_user_dir }}/.config/starship.toml"
    state: link
    force: true
  when: starship_sym.stat.islnk is not defined
