---
- name: Install
  community.general.homebrew:
    name:
      - luajit
      - neovim
    state: head

- name: Dependencies
  community.general.homebrew:
    name:
      - fd
      - fzf
      - ripgrep
      - tree-sitter
    state: latest

- name: Get stats of the neovim directory
  ansible.builtin.stat:
    path:  "{{ ansible_user_dir }}/.config/nvim"
  register: neovim_sym

- name: Print a debug message
  ansible.builtin.debug:
    msg: "Neovim path exists and is a symlink"
  when: neovim_sym.stat.islnk is defined and neovim_sym.stat.islnk

- name: Create symlink to queries directory
  ansible.builtin.file:
    src: "{{ ansible_user_dir}}/dotfiles/roles/neovim/files"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
  when: neovim_sym.stat.islnk is not defined
