---
- name: Install neovim build dependencies
  community.general.homebrew:
    state: present
    name:
      - ninja
      - libtool
      - automake
      - cmake
      - pkg-config
      - gettext

- name: Clone neovim
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim"
    dest: "{{ ansible_user_dir }}/.config/neovim"

- name: Build neovim
  ansible.builtin.shell:
    cmd: make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX={{ ansible_user_dir }}/.config/neovim && make install
    chdir: "{{ ansible_user_dir }}/.config/neovim"

- name: Get stats of the neovim directory
  ansible.builtin.stat:
    path:  "{{ ansible_user_dir }}/.config/nvim"
  register: neovim_sym

- name: Print a debug message
  ansible.builtin.debug:
    msg: "Neovim path exists and is a symlink"
  when: neovim_sym.stat.islnk is defined and neovim_sym.stat.islnk

- name: Create symlink to neovim directory
  ansible.builtin.file:
    src: "{{ ansible_user_dir}}/dotfiles/roles/neovim/files"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
  when: neovim_sym.stat.islnk is not defined
